# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "kind"
  #config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.network "private_network", ip: "10.10.10.80"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

  config.vm.provision "shell", path: "script.sh"
  config.vm.box_download_insecure=true
end
