# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  
  # variavel criada para armazenar comandos
  $script = <<-EOF
  sudo dnf install -y nginx
  sudo setenforce 0
  sudo systemctl enable --now nginx
  EOF

  # Criar 3 hosts
  # O que estiver dentro de server1 vale só para o mesmo, o mesmo acontece com server2 e server3
  # Os comandos que estiverem fora valem para todas as vms 

  # criar VM server1
  config.vm.define "server1" do |server1|
   # SO do box
   server1.vm.box = "almalinux/8"
   #hostname
   server1.vm.hostname = "server1"
   # Criar net privada e configurar ip estático
   server1.vm.network "private_network", ip: "10.10.10.11",
    virtualbox__intnet: "mynetwork"
   # NAT com encaminhamento de portas
   server1.vm.network "forwarded_port", guest: 80, host: 8081
   # Executar arquivo script-alma8.sh
   server1.vm.provision "shell", path: "script-alma8.sh"
  end 
  
  # criar VM server2
  config.vm.define "server2" do |server2|
   server2.vm.box = "almalinux/9"
   server2.vm.hostname = "server2"
   server2.vm.network "private_network", ip: "10.10.10.12",
    virtualbox__intnet: "mynetwork"
   # Executar comandos após o inline
   server2.vm.provision "shell", inline: "sudo yum install -y nginx; sudo setenforce 0; sudo systemctl enable --now nginx"
  end 
  
  # criar VM server3
  config.vm.define "server3" do |server3|
    server3.vm.box = "almalinux/9"
    server3.vm.hostname = "server3"
    server3.vm.network "private_network", ip: "10.10.10.13",
     virtualbox__intnet: "mynetwork"
    server3.vm.network "forwarded_port", guest: 80, host: 8083
    # Executar comandos da variavel $script
    server3.vm.provision "shell", inline: $script
  end 


  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "2048"
  end

  
 #config.vm.synced_folder "web/", "/var/www/html/"

 #config.vm.box_check_update = false
  
  # Ativa conexão insegura
  config.vm.box_download_insecure=true

end