# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  config.vm.hostname = "serverweb"
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

  config.vm.provision "shell", path: "script.sh"
  config.vm.synced_folder "web/", "/var/www/html/"

 # config.vm.box_check_update = false
  config.vm.box_download_insecure=true

end
