# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "generic-x64/rocky8"
  config.vm.hostname = "rocky8"
  config.vm.network "private_network", ip: "10.10.10.228"
  config.vm.network "forwarded_port", guest: 80, host: 8088
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "1024"
  end

  config.vm.provider "vmware_desktop" do |vb|
    vb.cpus = "1"
    vb.memory = "1024"
    vb.gui = true
  end

  #config.vm.provision "shell", path: "script.sh"
 # config.vm.synced_folder "web/", "/var/www/html/"

 # config.vm.box_check_update = false
  config.vm.box_download_insecure=true

end



