# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.vm.hostname = "kali"
  config.vm.network "private_network", ip: "10.10.10.50"
  #config.vm.network "forwarded_port", guest: 80, host: 8081

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "2048"
  end

  config.vm.box_download_insecure=true
end
