
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "server2019" do |server2019|
      server2019.vm.box = "gusztavvargadr/windows-server-2019-standard"
      #server2019.vm.network :forwarded_port, guest: 3389, host: 53389, id: "rdp", auto_correct: true
      
      server2019.vm.network "private_network", ip: "10.10.10.200"

      #server2019.vm.guest = :windows
      #server2016.vm.communicator = "winrm"
      server2019.vm.communicator = "winrm"

      server2019.winrm.username = "vagrant"
      server2019.winrm.password = "vagrant"

      server2019.vm.provider "virtualbox" do |vb|
        #vb.gui = true
        vb.name = "server2019"
        vb.cpus = "2"
        vb.memory = "2048"
        #vb.customize ["modifyvm", :id, "--vram", 128]
        #vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        #vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
      end

      server2019.windows.halt_timeout = 20
 

    end

    config.vm.define "server2019v1" do |server2019v1|
      server2019v1.vm.box = "gusztavvargadr/windows-server-2019-standard"
      #server2019.vm.network :forwarded_port, guest: 3389, host: 53389, id: "rdp", auto_correct: true
      
      server2019v1.vm.network "private_network", ip: "10.10.10.201"

      #server2019.vm.guest = :windows
      #server2016.vm.communicator = "winrm"
      server2019v1.vm.communicator = "winrm"

      server2019v1.winrm.username = "vagrant"
      server2019v1.winrm.password = "vagrant"

      server2019v1.vm.provider "virtualbox" do |vb|
        #vb.gui = true
        vb.name = "server2019v1"
        vb.cpus = "1"
        vb.memory = "2048"
        #vb.customize ["modifyvm", :id, "--vram", 128]
        #vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        #vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
      end

      server2019v1.windows.halt_timeout = 20
 

    end




    config.vm.define "server2019v2" do |server2019v2|
      server2019v2.vm.box = "gusztavvargadr/windows-server-2019-standard"
      #server2019.vm.network :forwarded_port, guest: 3389, host: 53389, id: "rdp", auto_correct: true
      
      server2019v2.vm.network "private_network", ip: "10.10.10.202"

      #server2019.vm.guest = :windows
      #server2016.vm.communicator = "winrm"
      server2019v2.vm.communicator = "winrm"

      server2019v2.winrm.username = "vagrant"
      server2019v2.winrm.password = "vagrant"

      server2019v2.vm.provider "virtualbox" do |vb|
        #vb.gui = true
        vb.name = "server2019v2"
        vb.cpus = "2"
        vb.memory = "2048"
        #vb.customize ["modifyvm", :id, "--vram", 128]
        #vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        #vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
      end

      server2019v2.windows.halt_timeout = 20
 

    end




    config.vm.define "win10" do |win10|
      win10.vm.box = "gusztavvargadr/windows-10"
  #    win11.vm.network :forwarded_port, guest: 3389, host: 53389, id: "rdp", auto_correct: true
      
      win10.vm.network "private_network", ip: "10.10.10.230"

      win10.vm.guest = :windows

      win10.vm.communicator = "winrm"

      # Admin user name and password
      win10.winrm.username = "vagrant"
      win10.winrm.password = "vagrant"

      win10.vm.provider "virtualbox" do |vb|
        #vb.gui = true
        vb.name = "win10"
        vb.cpus = "1"
        vb.memory = "2048"
        vb.customize ["modifyvm", :id, "--vram", 128]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
      end

      win10.windows.halt_timeout = 20
#      win10.vm.synced_folder ".", "/vagrant"

    end






  #config.windows.halt_timeout = 20
  #config.vm.synced_folder ".", "/vagrant"
  config.vm.box_download_insecure=true
end
