# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "generic-x64/oracle7"
  config.vm.hostname = "oracle7"
  config.vm.network "private_network", ip: "10.10.10.217"
  #config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "1024"
  end

  config.vm.provider "vmware_desktop" do |vb|
    vb.cpus = "1"
    vb.memory = "1024"
    vb.gui = true
  end

  #config.vm.provision "shell", path: "script.sh"
  #config.vm.synced_folder "web/", "/var/www/html/"

 # config.vm.box_check_update = false
  config.vm.box_download_insecure=true

end



