# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.communicator = "winrm"

  # Admin user name and password
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  config.vm.guest = :windows
  #config.windows.halt_timeout = 15

  config.vm.network "private_network", ip: "10.10.10.210",
   virtualbox__intnet: "mynetwork"
  # Acesso via 127.0.0.1:53389
  # Encaminhar rdp, ativar se necessário
  #config.vm.network :forwarded_port, guest: 3389, host: 53389, id: "rdp", auto_correct: true

  config.vm.provider "virtualbox" do |vb|
      #vb.gui = true
      vb.name = "win10"
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", 128]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
  end

  #tamanho da janela
  #config.rdp.width  = 1440 # default: 1024
  #config.rdp.height = 900  # default: 768
  config.windows.halt_timeout = 20
  config.vm.synced_folder ".", "/vagrant"
  config.vm.box_download_insecure=true
end
