# -*- mode: ruby -*-
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "server01"
  config.vm.network "private_network", ip: "10.10.10.210",
   virtualbox__intnet: "mynetwork"
  config.vm.network "forwarded_port", guest: 80, host: 8081

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

  config.vm.provision "shell", path: "script.sh"
  #config.vm.synced_folder "web/", "/var/www/html/"  

  config.vm.box_download_insecure=true
end
