# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "StefanScherer/windows_2016"
  #config.vm.communicator = "winrm"

  # Admin user name and password
  #config.winrm.username = "vagrant"
  #config.winrm.password = "vagrant"

  #config.vm.network "private_network", ip: "10.10.10.200",
  # virtualbox__intnet: "mynetwork"0

  #config.vm.guest = :windows
  #config.windows.halt_timeout = 15

  #config.vm.network "private_network", ip: "10.10.10.200"
  # Acesso via 127.0.0.1:53389
  # Encaminhar rdp, ativar se necessário
  #config.vm.network :forwarded_port, guest: 3389, host: 33389, id: "rdp", auto_correct: true

  config.vm.define "win7" do |win7|
      win7.vm.box = "stooj/windows7"
      win7.vm.network :forwarded_port, guest: 3389, host: 53389, id: "rdp", auto_correct: true
      
      win7.vm.network "private_network", ip: "10.10.10.200"

      win7.vm.guest = :windows
      win7.vm.communicator = "winrm"

      # Admin user name and password
      win7.winrm.username = "vagrant"
      win7.winrm.password = "vagrant"


      win7.vm.provider "virtualbox" do |vb|
        #vb.gui = true
        vb.name = "win7"
        vb.cpus = "1"
        vb.memory = "1024"
        vb.customize ["modifyvm", :id, "--vram", 128]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
      end
      
      win7.windows.halt_timeout = 20
      win7.vm.synced_folder ".", "/vagrant"
    
  end
  
  #config.windows.halt_timeout = 20
  #config.vm.synced_folder ".", "/vagrant"
  config.vm.box_download_insecure=true
end