# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  
  # variavel criada para armazenar comandos
  #$script = <<-EOF
  #sudo dnf install -y nginx
  #sudo setenforce 0
  #sudo systemctl enable --now nginx
  #EOF

  # Criar 3 hosts
  # O que estiver dentro de server1 vale só para o mesmo, o mesmo acontece com server2 e server3
  # Os comandos que estiverem fora valem para todas as vms 

  # criar VM control
  config.vm.define "ldapmaster" do |ldapmaster|
   # SO do box
   ldapmaster.vm.box = "eurolinux-vagrant/rocky-8"
   #hostname
   ldapmaster.vm.hostname = "ldapmaster"
   # Criar net privada e configurar ip estático
   ldapmaster.vm.network "private_network", ip: "10.10.10.11"
   # NAT com encaminhamento de portas
   ldapmaster.vm.network "forwarded_port", guest: 80, host: 8080
   ldapmaster.vm.network "forwarded_port", guest: 443, host: 8443
   # Executar arquivo script-alma8.sh
   #server1.vm.provision "shell", path: "script-alma8.sh"
  end 
  
  # criar VM worker01
  config.vm.define "client01" do |client01|
    client01.vm.box = "eurolinux-vagrant/rocky-8"
    client01.vm.hostname = "client01"
    client01.vm.network "private_network", ip: "10.10.10.12"
   # Executar comandos após o inline
   #server2.vm.provision "shell", inline: "sudo yum install -y nginx; sudo setenforce 0; sudo systemctl enable --now nginx"
  end 
  
  # criar VM worker02
  #config.vm.define "worker02" do |worker02|
  #  worker02.vm.box = "almalinux/8"
  #  worker02.vm.hostname = "worker02"
  #  worker02.vm.network "private_network", ip: "10.10.10.13"
    #server3.vm.network "forwarded_port", guest: 80, host: 8083
    # Executar comandos da variavel $script
    #server3.vm.provision "shell", inline: $script
  #end 


  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

  
 #config.vm.synced_folder "web/", "/var/www/html/"

 #config.vm.box_check_update = false
  
  # Ativa conexão insegura
  config.vm.box_download_insecure=true

end